[game_values]
starting_stacks = 200
big_blind = 2
small_blind = 1

[bet_sizes]
preflop = [0.5, 1.0]
flop = [0.33, 0.75, 1.5]
turn = [0.75, 1.5]
river = [0.75, 1.25]

[buckets]
flop = "data/clustering/flop_assignments"
turn = "data/clustering/turn_assignments"
river = "data/clustering/river_assignments"

[load_isets]
enabled = false #if this is false does not load any checkpoint
regret = ""
strategy = ""
offset = ""
iters = ""
