# checkpoint to write at end of run
[save_isets]
enabled = true
overwrite = true
regret = "data/runs/100M/regret.bin"
strategy = "data/runs/100M/strat.bin"
offset = "data/runs/100M/offsets.bin"
iters = "data/runs/100M/iters.bin"

[save_preflop]
enabled = true
overwrite = true
path = "data/runs/100M/preflop.csv"